function grafica_r18(zdata1, cdata1, X1, YMatrix1)
%CREATEFIGURE(ZDATA1, CDATA1, X1, YMATRIX1)
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Sep-2025 10:23:25

% Create figure
figure1 = figure;
colormap(jet);

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create mesh
mesh(zdata1,cdata1,'Parent',subplot1);

% Create xlabel
xlabel('Valor de r');

% Create zlabel
zlabel('Concentración (C)');

% Create title
title('Superficie de soluciones en función de r y tiempo','FontSize',14);
% Create ylabel
ylabel('Tiempo');

view(subplot1,[-37.5 30]);
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Parent',subplot2);

% Create xlabel
xlabel('Tiempo');

% Create title
title('Evolución temporal de la concentración para distintos r','FontSize',14);
% Create ylabel
ylabel('Concentración (C)');

box(subplot2,'on');
% Create legend
legend(subplot2,'show');

